from flask import Flask, request, jsonify
import wtmaintenance  
import wtloss  
import ckd2
import diebetes
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_jwt_extended import JWTManager, create_access_token, jwt_required, get_jwt_identity
import datetime
import logging
from flask_migrate import Migrate
# from wtloss import wtloss 

app = Flask(__name__)
app.secret_key = "your_secret_key"

# Database setup
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///users.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['JWT_SECRET_KEY'] = 'your_secret_key'

db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
jwt = JWTManager(app)
migrate = Migrate(app, db)

# Set up logging
logging.basicConfig(level=logging.INFO)

# User model
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(120), nullable=False)

    # Relationship to UserData
    user_data = db.relationship('UserData', backref='user', lazy=True)

# User Data model
class UserData(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    weight = db.Column(db.String(10), nullable=False)
    height = db.Column(db.String(10), nullable=False)
    objective = db.Column(db.String(50), nullable=False)
    work_category = db.Column(db.String(50), nullable=False)
    gender = db.Column(db.String(10), nullable=False)
    age = db.Column(db.Integer, nullable=False)  # Ensure age is part of UserData
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)

# Registration
@app.route('/register', methods=['POST'])
def register():
    data = request.get_json()
    username = data['username']
    email = data['email']
    password = data['password']

    hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
    new_user = User(username=username, email=email, password=hashed_password)

    db.session.add(new_user)
    db.session.commit()

    return jsonify({"message": "User registered successfully!"}), 201

# Login
@app.route('/login', methods=['POST'])
def login():
    data = request.get_json()
    email = data['email']
    password = data['password']

    user = User.query.filter_by(email=email).first()
    if user and bcrypt.check_password_hash(user.password, password):
        access_token = create_access_token(identity=user.id, expires_delta=datetime.timedelta(days=1))
        return jsonify(access_token=access_token), 200
    else:
        logging.warning(f"Failed login attempt for email: {email}")
        return jsonify({"message": "Invalid credentials!"}), 401

# Logout
@app.route('/logout', methods=['POST'])
def logout():
    session.clear()
    return jsonify({"message": "Successfully logged out"}), 200

# Create User Data (including weight loss diet plan)
# @app.route('/create-user-data', methods=['POST'])
# @jwt_required()
# def create_user_data():
#     current_user_id = get_jwt_identity()
#     user = db.session.get(User, current_user_id)  # Replaced deprecated method

#     if not user:
#         return jsonify({"message": "User not found"}), 404

#     data = request.get_json()
#     weight = data.get('weight')
#     height = data.get('height')
#     objective = data.get('objective')
#     work_category = data.get('work_category')
#     gender = data.get('gender')
#     age = data.get('age')  # Ensure 'age' is part of the form

#     if not all([weight, height, objective, work_category, gender, age]):
#         return jsonify({"message": "All fields are required"}), 400

#     try:
#         new_user_data = UserData(
#             user_id=current_user_id,
#             weight=weight,
#             height=height,
#             objective=objective,
#             work_category=work_category,
#             gender=gender,
#             age=age
#         )

#         db.session.add(new_user_data)
#         db.session.commit()

#         # Call the weight loss function if the objective is "weight loss"
#         if objective.lower() == "weight loss":
#             recipes = wtloss(float(weight), float(height), gender, int(age), work_category)
            
#             # Make sure the diet plan is structured in a way that is easy for Flutter to consume
#             # For example, assuming `recipes` is a list of dictionary items containing meal names and their respective details
#             return jsonify({
#                 "message": "User data created successfully!",
#                 "diet_plan": recipes  # Return the diet plan generated by wtloss
#             }), 201

#         return jsonify({"message": "User data created successfully!"}), 201

#     except Exception as e:
#         logging.error(f"Error creating user data: {str(e)}")
#         return jsonify({"message": "An error occurred while creating user data"}), 500

# Get User Details
@app.route('/user-details', methods=['GET'])
@jwt_required()
def user_details():
    current_user_id = get_jwt_identity()
    user = db.session.get(User, current_user_id)

    if not user:
        return jsonify({"message": "User not found"}), 404

    # Assuming `User` has `username` and `email` fields
    return jsonify({
        "username": user.username,
        "email": user.email
    }), 200





@app.route('/submit', methods=['POST'])
def submit():
    data = request.get_json()  # Get JSON data from the request
    # name = data['name']
    age = data['age']
    gender = data['gender']
    weight = data['weight']
    height = data['height']
    work = data['work']

    user_data = {
        # 'name': name,
        'age': age,
        'gender': gender,
        'weight': weight,
        'height': height,
        'work': work
    }

    return jsonify(user_data)  # Send the user data back to Flutter

@app.route('/weight-maintenance', methods=['POST'])
def weight_maintenance():
    data = request.get_json()
    weight = data['weight']
    height = data['height']
    gender = data['gender']
    age = data['age']
    work = data['work']

    # Call the wtmen function from wtmaintenance.py to get the recipes
    recipes = wtmaintenance.wtmen(weight, height, gender, age, work)

    return jsonify(recipes)  # Return the recipes in JSON format

@app.route('/weight-loss', methods=['POST'])
def weight_loss():
    data = request.get_json()
    weight = data['weight']
    height = data['height']
    gender = data['gender']
    age = data['age']
    work = data['work']

    # Call the wtloss function from wtloss.py to get the recipes
    recipes = wtloss.wtloss(weight, height, gender, age, work)

    return jsonify(recipes)  # Return the recipes in JSON format

    
@app.route('/chronic-kidney', methods=['POST'])
def chronic_kidney():
    data = request.get_json()
    weight = data['weight']
    height = data['height']
    gender = data['gender']
    age = data['age']
    work = data['work']

    # Call the wtloss function from wtloss.py to get the recipes
    recipes =ckd2.chronickidneydisease(weight, height, gender, age, work)

    return jsonify(recipes)  # Return the recipes in JSON format


@app.route('/diebetes', methods=['POST'])
def diebetes():
    try:
        # Parse input data
        data = request.get_json()
        weight = float(data['weight'])
        height = float(data['height'])
        gender = data['gender']
        age = int(data['age'])
        work = data['work']

        # Call the diabetes function
        if weight > 0 and height > 0:
            response = diebetes.diabetes(weight, height, gender, age, work)

            # Return the response based on the logic in diabetes.py
            return jsonify({
                "message": "Diabetes management function executed successfully!",
                "result": response  # Add any relevant data from `diabetes` function
            }), 200
        else:
            return jsonify({
                "message": "Invalid weight or height values!"
            }), 400

    except Exception as e:
        logging.error(f"Error in diebetes endpoint: {str(e)}")
        return jsonify({
            "message": "An error occurred while processing the request.",
            "error": str(e)
        }), 500


if __name__ == '__main__':
    app.run(debug=True)
